version: '3'
services:
  web:
    depends_on:
      - database
    build: .
    ports:
      - 4000:4000
    container_name: pa11y-dashboard
    links:
      - database:mongodb
  database:
    image: mongo:4.4
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart: always
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: